### ISSUE TITLE
Functionality of undo changes

### ISSUE THREAD

**Issue by silvasara** [jhcp/piStar#7]
I am using the piStar tool for an academic work and I am very lacking in the functionality of undoing some change. Are there any pretensions to implementing it?

**Comment by jhcp** [comment]
Hi, thanks for using the piStar tool! We do intend to implement ctrl+z in this tool, we know it's a pain for the user. However, first we need to update the documentation of the tool, which is lagging behind.

**Comment by jhcp** [comment]
The undo feature has been pushed to the repository. It currently supports only the undoing of deletes.
